export const subjects = [
  "English",
  "Science",
  "Filipino",
  "Mathematics",
  "Social Science",
  "General Education",
  "Professional Education",
  "Specialization",
  "Assessment of Learning",
  "Curriculum Development",
  "Child and Adolescent Development",
  "Educational Technology",
  "Principles of Teaching",
  "Social Dimension",
  "Teaching Profession",
  "Biological Science",
  "Physical Science",
];
